ignores: [
    # This is used by commitlint in .commitlintrc.js
    '@commitlint/config-conventional',

    # @todo: remove dep from main package, once i18next is moved to specific packages
    'ts-node',

    # Workspace packages
    'eslint-config-jwp',
    '@typescript-eslint/parser', # Required by eslint-config-jwp
    '@typescript-eslint/eslint-plugin', # Required by eslint-config-jwp
    'eslint-plugin-import', # Required by eslint-config-jwp

    'depcheck',
    'ts-node'
  ]
